replaceitem entity @s slot.inventory 0 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 1 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 2 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 3 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 4 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 5 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 6 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 7 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 8 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 9 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 10 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 11 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 12 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 13 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 14 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 15 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 16 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 17 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 18 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 19 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 20 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 21 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 22 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 23 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 24 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 25 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.inventory 26 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }

replaceitem entity @s slot.hotbar 0 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 1 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 2 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 3 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 5 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 6 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 7 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }
replaceitem entity @s slot.hotbar 8 stick 1 0 { "item_lock": { "mode": "lock_in_slot" }, "keep_on_death": {} }